### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by MarkHoeber** [MarkHoeber/tools-tech-syllabus#54]
All,

I updated my get_started_html repository (both the HTML and CSS file) to better demonstrate some of the things we talked about last week.  See: https://github.com/MarkHoeber/get_started_html

And the website created from this repository:  https://markhoeber.github.io/get_started_html/index.html

This example now uses a class and ID in the to set styles for certain elements.  Specifically, see if you can figure out why:

- the first article has a gray background
- the paragraph in the second article is bold
- the quotation paragraph is in italics

Think about the selectors used in the css file to format those elements.

**Comment by LJSchmidt** [comment]
Mark, I thought I was following all of the information and that it all made sense.  However, I can't figure out where to edit the CSS file for our class assignment.  I've tried putting my style rules a few different places, where it made sense to me.  One time I broke my little webpage, and all the other times no change has showed up at all.

I haven't found a demonstration that helps me.  I've tried several different exercises, successfully, but I just can't get it on GitHub.

Does the geographic placement on the CSS sheet matter?  For example, I thought that the "nav" section should be outside the body, since the two article links are at the top of their page, but placing my nav style rules above the body curly brace had no effect on the sheet.  Then I tried placing it inside the body brackets, and it broke.  I followed your explanation about how the most specific rule applies, but is it also tied to placement in the sheet?

**Comment by MarkHoeber** [comment]
@LJSchmidt  hi, the order of rules in the CSS file does not matter at all.  Each rule is processed independently.  There's no nesting of rules -- e.g., the body rule does not contain the rules for elements in the HTML that the body contains. However the rules of the body would apply to nested HTML elements unless those rules are overridden in another rule.

For example, if body defines font-size as 12pt, that will apply to all elements (such as nav or article) unless those elements have a different value for font-size.

But again, no nesting of rules in the css file itself.

**Comment by Techwriter2017** [comment]
Is there anyway to work that allows me to have three files open (CSS file, index.html, and one other) so that I can bounce between the three making edits without having to make commit each time that I want to change files?  It's about fast prototyping and testing changes before I put them into a repository.

**Comment by MarkHoeber** [comment]
@Techwriter2017   working through the browser, you can just open multiple tabs.
Otherwise, using local tools (GitHub Client and a text editor) would allow you to do so without committing changes before testing. see: https://desktop.github.com/
